---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This used to be python-skeleton-deployment to be better distinguishable, but a suffix of the kind that it is seems redundant.
  name: python-skeleton
  labels:
    app: python-skeleton-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-skeleton-label
  template:
    metadata:
      labels:
        app: python-skeleton-label
    spec:
      containers:
      - name: python-skeleton
        image: '{{ .Values.ImagePrefix }}/python-skeleton:{{ .Chart.AppVersion }}'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
