---
apiVersion: v1
kind: Service
metadata:
  # This used to be python-skeleton-service to be better distinguishable, but a suffix of the kind that it is seems redundant. It also determines the cluster domain.
  name: python-skeleton
spec:
  selector:
    app: python-skeleton-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
